### ISSUE TITLE
Error: Running the contributed command

### ISSUE THREAD

**Issue by simonhoss** [pinussilvestrus/vs-code-bpmn-io#44] opened 2019-11-11 12:40 UTC
Hi

Thank you for this extension. When I try to show the preview I get the following error:
```js
notificationsAlerts.ts:38 Error: Running the contributed command: 'extension.bpmn-preview' failed.
	at v._executeContributedCommand (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:527:959)
	at v.$executeContributedCommand (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:528:217)
	at f._doInvokeHandler (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:285)
	at f._invokeHandler (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:645:999)
	at f._receiveRequest (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:664)
	at f._receiveOneMessage (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:477)
	at c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:754
	at l.fire (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:104
	at l.fire (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:629)
	at c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:824
	at l.fire (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at f.acceptChunk (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:737)
	at c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:89
	at Socket.t (c:\Users\chsiho\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by pinussilvestrus** [comment] 2019-11-11 13:46
Hi @simonhoss, thanks for reaching out.

Can you give some further details about what version of the extension you use and what bpmn diagram you tried to preview? It would be easier for me to actually reproduce it, since on current `master` and version `v0.5.0` it works for me.

**Comment by simonhoss** [comment] 2019-11-12 14:18
I tried it with this process. 
![diagram](https://user-images.githubusercontent.com/1117667/68679153-9e0e7100-055f-11ea-9065-83de72876784.png)

I use the current version from the extensions from vscode

Here are my Infos from vscode:

```
Version: 1.40.0 (user setup)
Commit: 86405ea23e3937316009fc27c9361deee66ffbf5
Date: 2019-11-06T17:02:13.381Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134
```

**Comment by pinussilvestrus** [comment] 2019-11-12 14:26
Can you post the `XML` of the diagram?

**Comment by simonhoss** [comment] 2019-11-14 06:50
Sure.

```
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" id="Definitions_1mkkj7d" targetNamespace="http://bpmn.io/schema/bpmn" exporter="bpmn-js (https://demo.bpmn.io)" exporterVersion="5.1.2">
  <bpmn:process id="Process_1rl1b9s" isExecutable="false">
    <bpmn:startEvent id="StartEvent_1xao34m">
      <bpmn:outgoing>SequenceFlow_0jga9kg</bpmn:outgoing>
    </bpmn:startEvent>
    <bpmn:task id="Task_1r9i361">
      <bpmn:incoming>SequenceFlow_0jga9kg</bpmn:incoming>
      <bpmn:outgoing>SequenceFlow_0np162s</bpmn:outgoing>
    </bpmn:task>
    <bpmn:sequenceFlow id="SequenceFlow_0jga9kg" sourceRef="StartEvent_1xao34m" targetRef="Task_1r9i361" />
    <bpmn:endEvent id="EndEvent_1g1g819">
      <bpmn:incoming>SequenceFlow_0np162s</bpmn:incoming>
    </bpmn:endEvent>
    <bpmn:sequenceFlow id="SequenceFlow_0np162s" sourceRef="Task_1r9i361" targetRef="EndEvent_1g1g819" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1rl1b9s">
      <bpmndi:BPMNShape id="_BPMNShape_StartEvent_2" bpmnElement="StartEvent_1xao34m">
        <dc:Bounds x="156" y="81" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNShape id="Task_1r9i361_di" bpmnElement="Task_1r9i361">
        <dc:Bounds x="250" y="59" width="100" height="80" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0jga9kg_di" bpmnElement="SequenceFlow_0jga9kg">
        <di:waypoint x="192" y="99" />
        <di:waypoint x="250" y="99" />
      </bpmndi:BPMNEdge>
      <bpmndi:BPMNShape id="EndEvent_1g1g819_di" bpmnElement="EndEvent_1g1g819">
        <dc:Bounds x="412" y="81" width="36" height="36" />
      </bpmndi:BPMNShape>
      <bpmndi:BPMNEdge id="SequenceFlow_0np162s_di" bpmnElement="SequenceFlow_0np162s">
        <di:waypoint x="350" y="99" />
        <di:waypoint x="412" y="99" />
      </bpmndi:BPMNEdge>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

**Comment by pinussilvestrus** [comment] 2019-11-14 07:42
Thanks, I was able to reproduce this error on Windows. I'll investigate that.

**Comment by pinussilvestrus** [comment] 2019-11-14 07:53
Seems like the Extension is not able to find the file on the disk

```js
[2019-11-13 23:48:05.640] [exthost] [error] Error: ENOENT: no such file or directory, open '/C:/Users/IEUser/Desktop/diagram.bpmn'
	at Object.openSync (fs.js:447:3)
	at Object.func (electron/js2c/asar.js:138:31)
	at Object.func [as openSync] (electron/js2c/asar.js:138:31)
	at Object.readFileSync (fs.js:349:35)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at Object.fs.readFileSync (electron/js2c/asar.js:580:40)
	at BpmnModelerProvider.provideTextDocumentContent (c:\Users\IEUser\.vscode\extensions\salaboy.vs-code-bpmn-io-0.5.0\out\viewerProvider.js:20:27)
	at createPreview (c:\Users\IEUser\.vscode\extensions\salaboy.vs-code-bpmn-io-0.5.0\out\extension.js:63:35)
	at c:\Users\IEUser\.vscode\extensions\salaboy.vs-code-bpmn-io-0.5.0\out\extension.js:41:27
	at v._executeContributedCommand (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:527:863)
	at v.$executeContributedCommand (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:528:217)
	at f._doInvokeHandler (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:285)
	at f._invokeHandler (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:645:999)
	at f._receiveRequest (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:664)
	at f._receiveOneMessage (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:477)
	at c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:754
	at l.fire (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:104
	at l.fire (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at _.fire (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
	at t.PersistentProtocol._receiveMessage (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:629)
	at c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:824
	at l.fire (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
	at f.acceptChunk (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:737)
	at c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:89
	at Socket.t (c:\Users\IEUser\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) extension.bpmn-preview
````

Do you have something else in the extensions log? You can find them by doing inside VS Code
Ctrl+P --> Developer Show Logs --> Extension Host

**Comment by simonhoss** [comment] 2019-11-15 07:46
Yes. I can confirm.

I guess in the uri ist the file:/// missing

**Comment by pinussilvestrus** [comment] 2019-11-15 11:50
Will be fixed in the next release, cf. 26870da

**Closed** 2019-11-15 16:45 UTC
Labels: bug, os:windows
